theme: jekyll-theme-minimal
title: bADAboom data story
description: A mapping of the immune reactions to COVID-19
show_downloads: True
navigation:
  - title: Home
    url: /
  - title: Example
    url: example
